### ISSUE TITLE
can support kcp-go?

### ISSUE THREAD

**Issue by rendawudi** [Unit-X/kcp-cpp#6]
I try to use this main.cpp to connect kcp-go(golang) server,But failed

kcp-go can't accept any data from client

and kcp-go send data to client,but client can't get any data

main.cpp:
`KCPNetClient lKcpClient;

    KCPSettings lSettingsClient;
    if(lKcpClient.configureKCP(lSettingsClient,
                               gotDataClient,
                               noConnectionClient,
                               "127.0.0.1",
                               12345,
                               10,
                               nullptr)) {
        std::cout << "Failed to configure the KCP Client" << std::endl;
    }
 lKcpClient.sendData((const char*)lData.data(), 4000);`

main.go:
`package main

import (
    "log"

    "github.com/xtaci/kcp-go/v5"
)

func main() {

    if listener, err := kcp.ListenWithOptions("127.0.0.1:12345", nil, 10, 3); err == nil {
        // spin-up the client
        for {
            s, err := listener.AcceptKCP()
            s.SetNoDelay(1, 10, 2, 1)
            if err != nil {
                log.Fatal(err)
            }
            go handleEcho(s)
        }
    } else {
        log.Fatal(err)
    }
}

// handleEcho send back everything it received
func handleEcho(conn *kcp.UDPSession) {
    buf := make([]byte, 4096)
    for {
        n, err := conn.Read(buf)
        if err != nil {
            log.Println(err)
            return
        }
        println("get:" + string(buf[:n]))
        n, err = conn.Write(buf[:n])
        if err != nil {
            log.Println(err)
            return
        }
    }
}
`

**Comment by andersc** [comment]
Hi.

Just out of curiosity. Guess you found the error since you closed the ticket. Was there something we should do or know about?

Else thanks for contacting us.

/A
