### ISSUE TITLE
Can't this project communicate with kcp-go in go?

### ISSUE THREAD

**Issue by Cc28256** [Unit-X/kcp-cpp#7]
Does it support communication as a client and kcp-go server? My own test results are not good.

**Comment by andersc** [comment]
kcp-cpp is a C++ wrapper of the C API exposed by [kcp](https://github.com/skywind3000/kcp) so kcp-cpp is compatible with soluitons based on the original KCP implementation. From what I see is the GO implementation not based on the KCP C code and is therefore not tested to be compatible. You are most likely correct in your findings.

**Comment by Cc28256** [comment]
Okay, thank you.
